#[derive(Clone, Debug)]
pub struct AnalyzeOptions {
    pub filter_numt: bool,
    pub threads: usize,
    pub min_mapping_quality: u8,
    pub min_base_quality: u8,
    pub excluded_snp_flags: u16,
    pub numt_threshold: f64,
    pub allow_development_tags: bool,
    pub emit_evidence_graph: bool,
    pub max_evidence_observations: usize,
    pub max_phase_links: usize,
    pub max_phase_work: usize,
    pub max_phase_molecule_references: usize,
    pub max_result_bytes: usize,
    pub evidence_page_size: usize,
    pub min_architecture_molecules: usize,
    pub max_candidate_architectures: usize,
    pub architecture_max_distance: f64,
    pub architecture_ambiguity_margin: f64,
    pub architecture_min_overlap_fraction: f64,
    pub architecture_consensus_fraction: f64,
    pub architecture_optional_fraction: f64,
    pub architecture_stability_replicates: usize,
    pub architecture_seed: u64,
    pub molecule_id_tag: String,
    pub umi_tag: String,
    pub duplex_tag: String,
}

impl Default for AnalyzeOptions {
    fn default() -> Self {
        Self {
            filter_numt: true,
            threads: 1,
            min_mapping_quality: 20,
            min_base_quality: 10,
            excluded_snp_flags: 0xF00,
            numt_threshold: 0.30,
            allow_development_tags: false,
            emit_evidence_graph: false,
            max_evidence_observations: 5_000_000,
            max_phase_links: 1_000_000,
            max_phase_work: 20_000_000,
            max_phase_molecule_references: 5_000_000,
            max_result_bytes: 128 * 1024 * 1024,
            evidence_page_size: 4096,
            min_architecture_molecules: 2,
            max_candidate_architectures: 256,
            architecture_max_distance: 0.20,
            architecture_ambiguity_margin: 0.05,
            architecture_min_overlap_fraction: 0.50,
            architecture_consensus_fraction: 0.80,
            architecture_optional_fraction: 0.20,
            architecture_stability_replicates: 32,
            architecture_seed: 0x4d49_544f_4152_4348,
            molecule_id_tag: String::new(),
            umi_tag: String::new(),
            duplex_tag: String::new(),
        }
    }
}
